services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flaskapp
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpassword
    networks:
      - app-network
    
  # Flask Backend
  backend:
    build: .
    working_dir: /backend
    volumes:
      - .:/backend
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=postgresql://flaskuser:flaskpassword@postgres:5432/flaskapp
    depends_on:
      - postgres
    ports:
      - "8000:8000"   # Changed from "5000:5000" - Now using port 8000 on host
      - "8001:8001"   # Changed from "5001:5001"
    networks:
      - app-network
    command: flask run --host=0.0.0.0 --port=8000

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: